%% Differential Equations Final Project -- PART 2: Parabolic Cylinder Equation
% shima samadi , mahyas javaheri
% Term: 1404_05 Second Semester | Instructor: Dr. Shameli

clc;
clear;
close all;
fprintf('\n============================================================\n');
fprintf('PART 2: Parabolic Cylinder Equation\n');
fprintf('============================================================\n');
fprintf(['a) Derivation: let z = arctan(y/y''), i.e. y = r*sin(z), y'' = r*cos(z)\n' ...
         '   (Pruefer transformation). Differentiating both relations and using\n' ...
         '   the original ODE  y'''' = -(n + 0.5 - x^2/4)*y  to eliminate y'''', the r''\n' ...
         '   terms cancel between the two equations and what remains is a single\n' ...
         '   first-order ODE purely in z:\n' ...
         '       dz/dx = cos(z)^2 + (n + 0.5 - x^2/4) * sin(z)^2\n\n']);
n_vals = [1, 5, 15];
xspan2 = [0, 10];
colors = {'b', 'r', 'g'};
x_c2_all = cell(1, length(n_vals));
Y_c2_all = cell(1, length(n_vals));
x_turn_all = zeros(1, length(n_vals));
for idx = 1:length(n_vals)
    n = n_vals(idx);
    x_turn = 2*sqrt(n + 0.5);
    x_turn_all(idx) = x_turn;
    fprintf('------------------------------------------------------------\n');
    fprintf('n = %d\n', n);
    fprintf('-----------------------------------------------------------\n');
    % b) Direction field of the z-equation for this n, x in [0,10], z in [-pi/2,pi/2]
    [X, Z] = meshgrid(linspace(0, 10, 30), linspace(-pi/2, pi/2, 25));
    DZ = cos(Z).^2 + (n + 0.5 - X.^2/4).*sin(Z).^2;
    DX = ones(size(DZ));
    Lm = sqrt(DX.^2 + DZ.^2);
    DX = DX./Lm; DZ = DZ./Lm;
    figure('Name', sprintf('Part 2: Direction Field (n=%d)', n), 'NumberTitle', 'off');
    quiver(X, Z, DX, DZ, 0.5);
    grid on;
    xlabel('x');
    ylabel('z = arctan(y/y'')');
    title(sprintf('Direction Field for the z-Equation (n = %d)', n));
    axis([0 10 -pi/2 pi/2]);
    fprintf('b) Turning point: x_t = 2*sqrt(n+0.5) = %.4f\n', x_turn);
    fprintf(['   Prediction: for x < x_t, (n+0.5-x^2/4) > 0, so dz/dx = cos(z)^2 +\n' ...
             '   (positive)*sin(z)^2 >= 0 everywhere -> z keeps advancing through\n' ...
             '   increasing angles -> y = r*sin(z) crosses zero repeatedly ->\n' ...
             '   OSCILLATORY behaviour near x = 0.\n' ...
             '   For x > x_t, (n+0.5-x^2/4) < 0, so dz/dx = cos(z)^2 - |...|*sin(z)^2\n' ...
             '   can go negative; z then settles near a fixed angle instead of\n' ...
             '   advancing through further cycles -> y stops crossing zero -> the\n' ...
             '   original solution becomes MONOTONIC (grows or decays) for x > x_t.\n' ...
             '   So yes: x_t is exactly the critical value where the qualitative\n' ...
             '   behaviour of y(x) is expected to change.\n\n']);
    % c)Numerical solution of the ORIGINAL equation for this n, both IC sets,
    %    plotted together
    ode_p2 = @(x, Y) [Y(2); -(n + 0.5 - x^2/4)*Y(1)];
    [x_c1, Y_c1] = ode45(ode_p2, xspan2, [1; 0]);   % y(0)=1, y'(0)=0
    [x_c2, Y_c2] = ode45(ode_p2, xspan2, [0; 1]);   % y(0)=0, y'(0)=1
    x_c2_all{idx} = x_c2;
    Y_c2_all{idx} = Y_c2;
    figure('Name', sprintf('Part 2: Solutions for n = %d', n), 'NumberTitle', 'off');
    plot(x_c1, Y_c1(:,1), 'b-', 'LineWidth', 2); hold on;
    plot(x_c2, Y_c2(:,1), 'r--', 'LineWidth', 2);
    xline(x_turn, 'k:', 'LineWidth', 1.5);
    grid on;
    xlabel('x');
    ylabel('y(x)');
    title(sprintf('Parabolic Cylinder Solotion for n=%d (dotted line = turning point)', n));
    legend('y(0)=1, y''(0)=0', 'y(0)=0, y''(0)=1', 'x_t (turning point)');
    % Quantitative check: does the oscillation actually stop near x_ t, as predicted?
    before_mask = x_c2 < x_turn;
    after_mask  = x_c2 >= x_turn;
    zc_before = sum(diff(sign(Y_c2(before_mask,1))) ~= 0);
    zc_after  = sum(diff(sign(Y_c2(after_mask,1))) ~= 0);
    fprintf('c) Zero-crossings of the y(0)=0 solution: %d for x < x_t, %d for x >= x_t.\n', ...
            zc_before, zc_after);
    fprintf(['   This is consistent with the prediction from part (b): the solution\n' ...
             '   oscillates below the turning point ane the crossing rate drops off\n' ...
             '   above it. Ths cutoff is sharpest for larger n (an asymptotic/WKB-type\n' ...
             '   result),so for n =1 the transition is only mild, while for n = 15 the\n' ...
             '   oscillation essentially stops entirely once x >= x_t.\n\n']);
    % d)/e) Compare to the previous n value
    if idx > 1
        fprintf('%s) Comparing n = %d to n = %d:\n', 'd/e', n, n_vals(idx-1));
        fprintf('   Turning point moved from x_t = %.4f to x_t = %.4f.\n', ...
                x_turn_all(idx-1), x_turn);
        fprintf(['   The oscillatory region is wider, and within it the local\n' ...
                 '   "frequency" sqrt(n+0.5-x^2/4) is larger, so the n = %d curve\n' ...
                 '   oscillates faster (shorter local wavelength) and keeps oscillating\n' ...
                 '   over a longer stretch of x before transitioning to monotonic growth,\n' ...
                 '   compared to n = %d.\n\n'], n, n_vals(idx-1));
    end
end
fprintf('------------------------------------------------------------\n');
fprintf(['e) Overall trend as n increases (1 -> 5 -> 15): the turning point\n' ...
         '   x_t = 2*sqrt(n+0.5) grows (%.3f -> %.3f -> %.3f), the oscillatory region\n' ...
         '   widens, the oscillations get faster, and the eventual monotonic\n' ...
         '   growth beyond x_t becomes steeper for larger n.\n\n'], ...
         x_turn_all(1), x_turn_all(2), x_turn_all(3));
% f) Overlay comparison of the y(0)=0 solutions for n = 1,5, 15
figure('Name', 'Part 2: Comparison of y(0)=0 Solutions Across n', 'NumberTitle', 'off');
hold on;
for i = 1:length(n_vals)
    plot(x_c2_all{i}, Y_c2_all{i}(:,1), colors{i}, 'LineWidth', 2, ...
         'DisplayName', sprintf('n=%d', n_vals(i)));
end
grid on;
xlabel('x');
ylabel('y(x)');
title('Comparison of y(0)=0, y''(0)=1 Solutions for n = 1, 5, 15');
legend('show');
fprintf('------------------------------------------------------------\n');
fprintf(['f) Comparing all three y(0) = 0 solutions:\n' ...
         '   Similarities:\n' ...
         '     - All three curves start at the identical initial state\n' ...
         '       (y(0) = 0, y''(0) = 1).\n' ...
         '     - All exhibit oscillatory behaviour for x < x_t and transition to\n' ...
         '       monotonic (exponential-like) growth for x > x_t.\n' ...
         '   Differences:\n' ...
         '     - As n increases (1 -> 5 -> 15), the turning point\n' ...
         '       x_t = 2*sqrt(n+0.5) moves further to the right (x_t = %.2f -> %.2f -> %.2f).\n' ...
         '     - Higher n values give a higher oscillation frequency in the range\n' ...
         '       0 <= x < x_t, and the eventual monotonic growth sets in later but\n' ...
         '       rises more steeply.\n\n'], x_turn_all(1), x_turn_all(2), x_turn_all(3));
fprintf('--- Part 2 Execution Completed Successfully ---\n');